name: OVO
favicon: null
layout_spectrum: 0.6377491953317076
typography_spectrum: 0.5581414620392025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.996701882686466
  lightness: 0.6508378405123949
  saturation: 0.9516814763192087
  rhythmicContrast: 0.1463233339600265
purpose: []
