name: OVO
favicon: null
layout_spectrum: 0.14132
typography_spectrum: 0.6029
title: 'Design & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#378aaa'
    - '#0d5c7d'
    - '#a9dcef'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
